esphome:
  name: standing-desk
  platform: ESP8266
  board: d1_mini
  project:
    name: tj_horner.wifi_desk_controller
    version: "0.0.8"

logger:
  level: DEBUG

dashboard_import:
  package_import_url: github://tjhorner/wifi-desk-controller/firmware/config.yaml

packages:
  standing_desk: github://tjhorner/esphome-standing-desk/configs/template.yaml
  # Make sure to change DESK_BRAND to your desk's brand (either uplift_v2 or fully_jarvis)
  desk_config: github://tjhorner/esphome-standing-desk/configs/desks/DESK_BRAND.yaml

wifi:
  ssid: "ssid_that_should_always_fail"
  # Required to support hidden networks.
  # Best to remove it if you don't have one.
  fast_connect: true
  ap:
    ssid: "Standing Desk Controller"
    password: "hunter2hunter2"

captive_portal:

improv_serial:

api:
  password: ""
  reboot_timeout: 0s

web_server:
  port: 80

ota:
  password: ""
